Change max amount of tries to 40 as well as stopping the application if it failed to start

diff --git a/.github/workflows/owasp_zap.yml b/.github/workflows/owasp_zap.yml
--- a/.github/workflows/owasp_zap.yml
+++ b/.github/workflows/owasp_zap.yml
@@ -65,7 +65,7 @@ jobs:
 
       - name: Wait for the application to start
         run: |
-          for i in {1..30}; do
+          for i in {1..40}; do
             if curl -s http://localhost:8081/ >/dev/null; then
               echo "App is running!"
               break
@@ -74,6 +74,8 @@ jobs:
               sleep 5
             fi
           done
+          echo "application faile to start"
+          exit 1
       
       - name: Create report directory with proper permissions
         run: mkdir -p "$(pwd)/zap-report" && chmod 777 "$(pwd)/zap-report"
